"""post model

Revision ID: 07d792d54f58
Revises: 5f979121dce1
Create Date: 2022-01-21 11:52:51.687318

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '07d792d54f58'
down_revision = '5f979121dce1'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
