"""post model

Revision ID: 23309c8c13ad
Revises: 50fcaad25179
Create Date: 2022-01-18 16:33:10.958256

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '23309c8c13ad'
down_revision = '50fcaad25179'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
