"""post model

Revision ID: 3a0293211932
Revises: 3e32f3b4e68d
Create Date: 2022-01-19 14:48:18.079206

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3a0293211932'
down_revision = '3e32f3b4e68d'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
