"""post model

Revision ID: 3e32f3b4e68d
Revises: 80473b824fcd
Create Date: 2022-01-19 13:27:02.028640

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3e32f3b4e68d'
down_revision = '80473b824fcd'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
