"""post model

Revision ID: 50fcaad25179
Revises: 824fc58260ba
Create Date: 2022-01-18 16:29:28.642191

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '50fcaad25179'
down_revision = '824fc58260ba'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
