"""post model

Revision ID: 5f979121dce1
Revises: 3a0293211932
Create Date: 2022-01-21 10:44:48.817650

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5f979121dce1'
down_revision = '3a0293211932'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
