"""post model

Revision ID: 74336d2c41e9
Revises: 9afab4bcc236
Create Date: 2022-01-21 12:08:20.416006

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '74336d2c41e9'
down_revision = '9afab4bcc236'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
