"""post model

Revision ID: 80473b824fcd
Revises: 4ec36b7c5c28
Create Date: 2022-01-19 13:20:20.610323

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '80473b824fcd'
down_revision = '4ec36b7c5c28'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
