"""post model

Revision ID: 80e22a5fd0fd
Revises: 8590605a75ee
Create Date: 2022-01-18 16:57:54.243958

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '80e22a5fd0fd'
down_revision = '8590605a75ee'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
