"""post model

Revision ID: 818fc3bbc28a
Revises: 80e22a5fd0fd
Create Date: 2022-01-18 17:03:42.768008

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '818fc3bbc28a'
down_revision = '80e22a5fd0fd'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Unicode(length=255), nullable=False))
        batch_op.drop_column('title')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
