"""post model

Revision ID: 824fc58260ba
Revises: 46ba77141a59
Create Date: 2022-01-18 16:25:17.034326

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '824fc58260ba'
down_revision = '46ba77141a59'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
