"""post model

Revision ID: 8590605a75ee
Revises: d9c21c761129
Create Date: 2022-01-18 16:44:42.244543

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8590605a75ee'
down_revision = 'd9c21c761129'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
