"""post model

Revision ID: 9afab4bcc236
Revises: 07d792d54f58
Create Date: 2022-01-21 11:55:17.339697

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9afab4bcc236'
down_revision = '07d792d54f58'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
